import type { INodeProperties } from 'n8n-workflow';

const showOnlyForPersonList = {
	operation: ['list'],
	resource: ['person'],
};

export const personListDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: showOnlyForPersonList },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		displayOptions: {
			show: {
				...showOnlyForPersonList,
				returnAll: [false],
			},
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: showOnlyForPersonList },
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				description: 'Filter by a part of the address (street, city, or post code)',
			},
			{
				displayName: 'Company',
				name: 'company',
				type: 'string',
				default: '',
				description: 'Filter by company name',
			},
			{
				displayName: 'Created Max',
				name: 'created_time_max',
				type: 'dateTime',
				default: '',
				description: 'Return only persons created before this date',
			},
			{
				displayName: 'Created Min',
				name: 'created_time_min',
				type: 'dateTime',
				default: '',
				description: 'Return only persons created after this date',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				description: 'Filter by email address',
			},
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				description: 'Filter by first name',
			},
			{
				displayName: 'IDs',
				name: 'ids',
				type: 'string',
				default: '',
				description: 'Comma-separated list of person IDs to retrieve',
				placeholder: 'e.g. 1,2,3',
			},
			{
				displayName: 'Last Name',
				name: 'last_name',
				type: 'string',
				default: '',
				description: 'Filter by last name',
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				default: '',
				description: 'Filter by phone number',
			},
			{
				displayName: 'Salutation',
				name: 'salutation',
				type: 'options',
				options: [
					{ name: '(No filter)', value: '' },
					{ name: 'Couple', value: 'couple' },
					{ name: 'Diverse', value: 'diverse' },
					{ name: 'Family', value: 'family' },
					{ name: 'Miss', value: 'Miss' },
					{ name: 'Mr.', value: 'Mr.' },
					{ name: 'Mrs.', value: 'Mrs.' },
					{ name: 'Ms.', value: 'Ms.' },
				],
				default: '',
				description: 'Filter by salutation',
			},
			{
				displayName: 'Search ID',
				name: 'search_id',
				type: 'number',
				default: 0,
				description: 'Filter by saved smart search ID',
			},
			{
				displayName: 'Tag IDs',
				name: 'tag_ids',
				type: 'string',
				default: '',
				description: 'Comma-separated list of tag IDs to filter by',
				placeholder: 'e.g. 10,20',
			},
			{
				displayName: 'Updated Max',
				name: 'updated_max',
				type: 'dateTime',
				default: '',
				description: 'Return only persons updated before this date',
			},
			{
				displayName: 'Updated Min',
				name: 'updated_min',
				type: 'dateTime',
				default: '',
				description: 'Return only persons updated after this date',
			},
		],
	},
];
